Repository visimp/visimp, pull requests merged in 2024-09, with the labels that each got.

#112 Adapt docs for use with visimp-pages
  _index.md
  docs/CONFIG.md
  docs/INTRO.md
  docs/contributing/GUIDELINES.md
  docs/contributing/LAYER.md
  docs/contributing/_index.md
  docs/languages/IDRIS.md
  docs/languages/_index.md
  docs/layers/LANGUAGES.md
  docs/layers/_index.md
  lua/visimp/pak/git.lua
Labels: documentation

#109 Custom greeter
  docs/CONFIG.md
  docs/layers/GREETER.md
  lua/visimp/layers/greeter.lua
  lua/visimp/setup.lua
Labels: enhancement

#115 Fix ltex default settings, documentation guidelines and typos/capitalization/style fixes via ltex
  docs/CONFIG.md
  docs/contributing/GUIDELINES.md
  docs/contributing/LAYER.md
  docs/languages/GLEAM.md
  docs/layers/BLANKLINE.md
  docs/layers/CMP.md
  docs/layers/DIAGNOSTICS.md
  docs/layers/FUGITIVE.md
  docs/layers/GREETER.md
  docs/layers/LANGUAGES.md
  docs/layers/LSP.md
  docs/layers/LTEX.md
  docs/layers/RAINBOW.md
  docs/layers/STATUSLINE.md
  docs/layers/THEME.md
  docs/layers/TREESITTER.md
  docs/layers/WHICHKEY.md
  docs/layers/ZEN.md
  lua/visimp/language.lua
  lua/visimp/languages/c.lua
  lua/visimp/languages/dart.lua
  lua/visimp/layers/ltex.lua
Labels: bug, documentation
